import type { NextPage } from 'next';
import Head from 'next/head';
import AddCommentForm from '../components/AddCommentForm';
import CommentList from '../components/CommentList';
import { currentUser } from '../data/data';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-screen-md m-auto">
        <CommentList />
        <AddCommentForm
          isReply={false}
          replyingTo="null"
          replyingToId={-1}
          hideForm={() => {}}
          currentUser={currentUser}
        />
      </main>
    </div>
  );
};

export default Home;
